apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws-cn:iam::749722169113:user/github-ci
      username: github-ci
      groups:
        - system:masters